### ISSUE TITLE
SPIKE: Charset research

### ISSUE THREAD

**Issue by willKim19** [aj-may/piquo#6]
Apparently some unicode (emojis in particular) might count for more than 1 character. All emojis should count as one character, we should do some research into how we can ensure all characters are really one character each.

**Comment by aj-may** [comment]
@willKim19 

Google firestorm does not handle multibyte chars correctly when calculating a string length.  This issue has been mitigated by increasing the limit of the firestore rules to `15` (assuming 3 byte chars `3 * 5 = 15`), and truncating the display of additional chars (#28)
